---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
#install:
#  - pip install docker
#  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
#script:
#  - cd gowtham/ && molecule test
notifications:
  email:
   recipients:
     - gowthamshankar09@gmail.com
     - monisha1410@gmail.com
   on_success: always # default: change
   on_failure: always # default: always
jobs:
  include:
    - stage: npm release
      install:
        - pip install docker
        - pip install molecule
      script: 
        - cd gowtham 
        - molecule test
    - stage: new stage
      script: echo "new stage2"
    - stage: final stage
      script: echo "final stage"
    - stage: super final stage
      script: ls
