---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install docker
  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
script:
  - cd gowtham/ && molecule test
notifications:
  email:
   recipients:
     - gowthamshankar09@gmail.com
