---
# tasks file for gowtham shankar
- name: Install docker
  yum:
   name: docker
   state: present

- name: create file
  file:
   path: /etc/docker/daemon.json
   state: touch
   modification_time: "preserve"
   access_time: "preserve"
